### PR TITLE
Switch to poetry

### PR DESCRIPTION
**Pull request by dcermak**

### CODE REVIEW

**Comment by dcermak** [comment]
Github actions run: https://github.com/dcermak/obs-service-replace_using_package_version/actions/runs/1778819749

**Comment by davidcassany** [comment]
@dcermak so far looks good to me. I have not had a chance to test it out in my env. I still need to figure out how to use poetry on my openSUSE Leap 15.3 env, but this is really promising since you also adapted the CI to use github actions.

Thanks much for the contribution!

However I am wondering if we shouldn't also adapt https://build.opensuse.org/package/show/Virtualization:containers/obs-service-replace_using_package_version before merging (or test it at least somewhere else). Whatever we end up using needs to build in OBS and the spec should be adapted.

**Comment by dirkmueller** [comment]
(Please note that the openSUSE python singlespec macros are not able to deal with poetry packages yet)

**Comment by dcermak** [comment]
> However I am wondering if we shouldn't also adapt https://build.opensuse.org/package/show/Virtualization:containers/obs-service-replace_using_package_version before merging (or test it at least somewhere else). Whatever we end up using needs to build in OBS and the spec should be adapted.

We should, but if you dare to take the risk, we can do that in a separate PR.

> (Please note that the openSUSE python singlespec macros are not able to deal with poetry packages yet)

But they should be able to deal with wheels from pypi, right? So we could simply push this Pypi and treat it like every other python package.

**Comment by davidcassany** [comment]
> We should, but if you dare to take the risk, we can do that in a separate PR.

Ok, I see you have a plan, going to trust you then 👍🏽

**Review by davidcassany — APPROVED** [review]

**Comment by davidcassany** [comment]
@dcermak you should have write access now to the repository, I encourage you to merge or merge and squash by yourself. Merging requires a review now and I already approved it.

**Comment by dcermak** [comment]
Thanks for your trust @davidcassany!

**Pull request merged**
