### PR TITLE
Fix default value for empty or missing version

### LINKED ISSUE #45: pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: ''
Staging projects received an update for python-setuptools to version 67.6.0

This service fails to parse version strings in a few builds:

e.g. https://build.opensuse.org/package/live_build_log/openSUSE:Factory:Staging:L/kubic-pause-image/images/x86_64

```
[    9s] Running build time source services...
[   10s] Traceback (most recent call last):
[   10s]   File "/usr/lib/obs/service/replace_using_package_version", line 251, in <module>
[   10s]     init(__name__)
[   10s]   File "/usr/lib/obs/service/replace_using_package_version", line 248, in init
[   10s]     main()
[   10s]   File "/usr/lib/obs/service/replace_using_package_version", line 133, in main
[   10s]     version = find_package_version(command_args['--package'], rpm_dir)
[   10s]   File "/usr/lib/obs/service/replace_using_package_version", line 164, in find_package_version
[   10s]     version = parse_version('')
[   10s]   File "/usr/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/version.py", line 197, in __init__
[   10s]     raise InvalidVersion(f"Invalid version: '{version}'")
[   10s] pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: ''
[   10s] service run failed for service 'replace_using_package_version'
```

The 'replacing empty string' could very well hint at an error in the build where we try to find a version number of a package that does not exist? If so, this error might be a very nice addition to catch those things; otherwise the error should be fixed

### PR DESCRIPTION
**Pull request by davidcassany**
Fixes #45

### CODE REVIEW

**Comment by dcermak** [comment]
@davidcassany The patch lgtm, but it looks like the tests are failing now.

**Comment by davidcassany** [comment]
> @davidcassany The patch lgtm, but it looks like the tests are failing now.

Yes, gonna try to address them today eve

**Comment by davidcassany** [comment]
@dcermak fixed now, I'd say this is ready to be merged

**Comment by davidcassany** [comment]
Gonna cut a release and prepare a submission to factory

**Pull request merged**
